### PR TITLE
Fix for Issue #67

### PR DESCRIPTION
**Pull request by JensPiegsa**
https://github.com/winterstein/Eclipse-Markdown-Editor-Plugin/issues/67

### CODE REVIEW

**Comment by winterstein** [comment]
Hello Jens,

Thank you for the pull request. I'm tied up with other work.
To get this merged in -- can I ask: What testing have you done?

Could you try the text below?
If this renders fine, then let me know the good news, and I'll merge
your fix in.

# Test (h1) #
## Headers (h2)
## Another h2 header straight away
Some text
## Another h2 header after text


### An h3 header after some whitespace ###

An underlined header
-----------------------------

Another underlined header
====================

```
# Comments in a code block
# Should be left alone
```

Thank you for both spotting and fixing this issue.

Kind regards,
 - Daniel

**Comment by JensPiegsa** [comment]
Hello Daniel,

thanks for your quick reply. I haven't touched your test class, but 
used the updated class file within my Eclipse installation and tested
the editor / outline against our project documentation for proper
functioning.

I now ran your test content manually. The results look fine.

Regards,
Jens

test md_eclipse

**Comment by winterstein** [comment]
Thanks Jens!

**Comment by JensPiegsa** [comment]
Glad to be of help.

**Comment by paulvi** [comment]
Please add to https://github.com/winterstein/Eclipse-Markdown-Editor-Plugin#history

**Pull request merged**
